### ISSUE TITLE
Nie działa api pukawki.

### ISSUE THREAD

**Issue by lock292** [d0naciak/AMXX-Sklep-SMS#1]
Proszę o aktualizacje api pukawki bo aktualnie działa tylko cssetti które mnie nie interesuje..
Pozdrawiam.

**Comment by black0041** [comment]
Podpinam się, sklepsms wysyła informacje na czacie do gracza, że kod jest sprawdzany lub coś w tym stylu i nic dalej się nie dzieje.

**Comment by d0naciak** [comment]
Poprawione
